name: tests
on:
  push:
    branches:
      - 'master'
      - 'renovate/**'
    tags:
      - '*.*.*'
  pull_request:
    branches:
      - 'master'

permissions:
  contents: read
  pull-requests: write

jobs:
  unit-tests:
    name: unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6.0.9
        with:
          version: 10.33.4
      - uses: actions/setup-node@v6
        with:
          node-version: 24.16.0
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run unit tests
        run: pnpm test
